language: java
sudo: false
jdk:
  - oraclejdk8
env:
  - CASSANDRA_VERSION=3.7
install: mvn install -DskipTests=true -Dcassandra.version=$CASSANDRA_VERSION
script: mvn test -Dcassandra.version=$CASSANDRA_VERSION
cache:
  directories:
    - $HOME/.m2
